### ISSUE TITLE
`Access is denied` errors in IE9

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/n-messages#11]
Lots of `Access is denied` errors

![screen shot 2016-06-03 at 16 44 18](https://cloud.githubusercontent.com/assets/74132/15784461/7c420cc4-29aa-11e6-9cc5-b3726938e044.jpeg)

Seems to happen in here - https://github.com/Financial-Times/n-messages/blob/master/src/initialise.js#L21

**Comment by ifyio** [comment]
Yes saw this today. Its because of cors and only happens in IE 9

**Comment by ifyio** [comment]
looking into it

**Comment by ifyio** [comment]
Fixed by https://github.com/Financial-Times/n-messages/pull/13
